### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by alexoliva91** [oskarsh/Yin-Yang#204] opened 2023-05-30 06:55 UTC
### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [X] Atom
- [X] Brave
- [X] Colors
- [X] Custom Script
- [X] Firefox
- [X] Gedit
- [X] GTK
- [X] Konsole
- [X] Kvantum
- [X] Only Office
- [X] System
- [X] VSCode
- [X] Wallpaper

### Affected versions

- Yin-Yang version: 3.2.4
- Relevant application version: 
- Python version: 3.11.3
- Qt version: 5.15.9

### Additional notes

When I try to run the app, it doesn't start. If run from the terminal I get the following error:

> Using default configuration values.
> Traceback (most recent call last):
>   File "/opt/yin-yang/main.py", line 13, in <module>
>     from src import daemon_handler
>   File "/opt/yin-yang/src/daemon_handler.py", line 7, in <module>
>     from src.config import ConfigWatcher, config
>   File "/opt/yin-yang/src/config.py", line 476, in <module>
>     config = ConfigManager()
>              ^^^^^^^^^^^^^^^
>   File "/opt/yin-yang/src/config.py", line 181, in __init__
>     self.load()
>   File "/opt/yin-yang/src/config.py", line 248, in load
>     pl.theme_light = config_loaded['plugins'][pl.name.lower()]['light_theme']
>     ^^^^^^^^^^^^^^
>   File "/opt/yin-yang/src/plugins/konsole.py", line 42, in theme_light
>     self.update_profile(False, value)
>   File "/opt/yin-yang/src/plugins/konsole.py", line 179, in update_profile
>     profile_config['Appearance']['ColorScheme'] = theme
>     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 979, in __getitem__
>     raise KeyError(key)
> KeyError: 'Appearance'

The app works again if I disable the konsole plugin from the _init_.py in the plugins folder.

**Comment by lunar-natalie** [comment] 2023-06-27 08:13
I'm also having this issue when running after building from the git source on Debian 12 / Plasma 5.27.5. @alexoliva91 Your temporary patch works for me too.

**Comment by l0drex** [comment] 2023-07-14 11:41
Duplicate of #200

**Closed by l0drex** 2023-07-14 11:41 UTC
Labels: bug
