### ISSUE TITLE
QDBusConnection: error: could not send signal to service ""

### ISSUE THREAD

**Issue by etkecc** [oskarsh/Yin-Yang#218] opened 2023-09-13 07:37 UTC
### Describe the bug

When toggling a theme, the following log output appears:

```
Successfully applied the color scheme BreezeDark to your current Plasma session
QDBusConnection: error: could not send signal to service "" path "//home/USER/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/USER/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/USER/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/USER/.config/kdedefaults/kdeglobals
```

note that path has a double slash at the start (`//home/...`) instead of a single one (`/home/...`)

### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [ ] Atom
- [ ] Brave
- [x] Colors
- [ ] Custom Script
- [x] Firefox
- [ ] Gedit
- [x] GTK
- [ ] Konsole
- [ ] Kvantum
- [ ] Only Office
- [x] System
- [ ] VSCode
- [ ] Wallpaper

### Affected versions

- Yin-Yang version:

- Relevant application version: 3.2
- Python version: 3.11.5
- Qt version:

**Comment by l0drex** [comment] 2023-10-07 09:31
Duplicate of #92

**Closed by l0drex** 2023-10-07 09:31 UTC
Labels: bug
