### ISSUE TITLE
 No schema “org.gnome.gedit.preferences.editor”` unneccessary in some systems?

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#172] opened 2023-03-07 12:29 UTC
Could the error `No such schema “org.gnome.gedit.preferences.editor”` be suppressed in systems not needing that schema?

**Comment by l0drex** [comment] 2023-03-07 22:40
Infact, we should completely subpress it. If it is not available, then the plugin will be hidden.

**Comment by l0drex** [comment] 2023-03-07 23:11
Duplicate of #140

**Closed by l0drex** 2023-03-07 23:11 UTC
