### ISSUE TITLE
JSON files with comments or trailing commas are not supported

### ISSUE THREAD

**Issue by rgeorgiev583** [oskarsh/Yin-Yang#120] opened 2022-04-16 11:09 UTC
I managed to reproduce this with the VSCode plugin, where the parsing of `settings.json` file failed.  However, I suppose that it would be reproducible with the Firefox plugin as well (which also parses JSON files).
When I execute `yin-yang -t` from the command line, the following error messages appear:
* `2022-04-16 13:57:39,999 ERROR - src.yin_yang: Error while changing the theme in plugin VS Code`
* `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 5 (char 558)`
After the first `yin-yang` run, I noticed that there are comments in my `settings.json` file, and the mentioned line and column number matched the `//` sequence which begins the first comment.  After removing all comments from the file, the same error persisted on the second run.  However, now it was on the line containing the closing `}` of a JSON object with a trailing comma after its last property:
```json
    "files.associations": {
        ".clang-format": "yaml",
        ".nvimrc": "viml",
    },
```

I suppose that is caused by limitations in the `json` Python module.  It's up to the author to decide if it's feasible to use another module which supports these syntax features.

**Comment by oskarsh** [comment] 2022-04-25 06:46
@rgeorgiev583 thanks for the bug report, I was not aware of this. However I will not going to fix this issue since this is not a breaking bug. If you are interested in collaboration feel free to take up that task.

**Comment by flying-sheep** [comment] 2022-12-09 16:08
We’d need something like `tomli` for JSON-with-comments to properly support VS Code.

I don’t want this project to get rid of my comments and formatting in my VS Code config.

**Comment by flying-sheep** [comment] 2022-12-23 15:55
What’s a “breaking bug”? This makes Yin-Yang incompatible with any VS Code config that uses comments or trailing commas, which is almost all of them.

**Comment by l0drex** [comment] 2024-04-10 18:54
Duplicate of #84

**Closed by l0drex** 2024-04-10 18:54 UTC
Labels: bug, wontfix
