### ISSUE TITLE
`yin-yang.timer` changes theme at 20:00 despite what is configured in the UI

### ISSUE THREAD

**Issue by bphd** [oskarsh/Yin-Yang#147] opened 2022-12-12 17:06 UTC
Oh, and about the PR for `konsole`. It doesn't make it for the principal reported problem that it claims to solve, about `yakuake`. It doesn't changes anything.

It should:

* Change theme for all `konsole` terminal family (`yakuake`...)
* Change it in live, without the need to close CLI session or window
* Change "Color scheme & font"
* Change "Skin"
* Let the choice to the user about those two parameters (preferably retreiving and list available themes, rather than letting the user guess the name he should input)

**Comment by bphd** [comment] 2022-12-12 21:45
Something else than 20:00. I change it often to test if it will work and to adapt to my situation, but still, 20:00 military

And before using `systemd` it was even worse. It didn't changed automatically at all

**Comment by l0drex** [comment] 2022-12-13 09:34
Did you set manual times or did you use the sunrise? If you used the sunrise, did you also set your location automatically?

**Comment by bphd** [comment] 2022-12-13 13:13
> Did you set manual times or did you use the sunrise? If you used the sunrise, did you also set your location automatically?

All manual and configured. And even with sunrise unconfigured, the default position don't give 20:00 each day. For me either the service don't search the data where it should, either the UI don't write it where it should. Maybe something to see with root/user?

**Comment by flying-sheep** [comment] 2022-12-23 15:52
The file just uses fixed times and is therefore incompatible with using sunrise/sunset times.

https://github.com/oskarsh/Yin-Yang/blob/a82bcb2485845ea58c60794047a98762278623e8/resources/yin_yang.timer#L5-L6

One quick fix would be to run it every half hour or so, so it triggers maximally about 30 minutes after sunrise/sunset.

Another fix would be to have two timers, the second one editing the first timer file to contain correct sunrise/sunset times. That way times would maximally be off by one minute or so (because yesterday’s sunset/sunrise times are used)

**Comment by l0drex** [comment] 2022-12-23 18:00
Well in theory, the times should be set to sunrise and sunset times once the option is selected from the UI through the [daemon handler](https://github.com/oskarsh/Yin-Yang/blob/master/src/daemon_handler.py). On every start, they get updated as well to account for differences over the year.

**Comment by flying-sheep** [comment] 2022-12-23 19:37
You should use `platformdirs`’ data dir instead of hardcoding that path. If users override `XDG_DATA_DIR`, their systemd files are in there instead. Platformdirs handles this.

That being said I don't override it, so it should work for me. I can check why it doesn't. Maybe because #120 makes it crash on my system when it fails to read my VS Code config file?

**Comment by bphd** [comment] 2022-12-23 19:42
> run it every half hour or so, so it triggers maximally about 30 minutes after sunrise/sunset.

You can run it as often as you want, it will not do anything until it's past 20. And it will be way too late for me. The idea would be for Yin-Yang to modify this file aswell when changing parameters on the GUI. Like I said "either the UI don't write it where it should" and here it should write in this place

> On every start, they get updated as well

Yeah, using the same mechanism as what is acutually used to modify this file aswell

**Comment by flying-sheep** [comment] 2022-12-25 18:02
@bphd If I understand correctly, that’s not how it’s intended to work. This code:

https://github.com/oskarsh/Yin-Yang/blob/a82bcb2485845ea58c60794047a98762278623e8/src/daemon_handler.py?rgh-link-date=2022-12-23T18%3A00%3A05Z#L29-L36

is intended to update the sunrise/sunset times in `yin_yang.timer` and to make systemd reload this timer.

That means that at latest at the next sunrise/sunset, the timer is set to (almost) accurate times.

@l0drex this is my config:

```console
$ cat .config/yin_yang/yin_yang.json | from json | reject plugins
╭─────────────────┬───────────────────╮
│ version         │ 3.20              │
│ running         │ false             │
│ dark_mode       │ true              │
│ mode            │ sunset to sunrise │
│                 │ ╭───┬───────╮     │
│ coordinates     │ │ 0 │ 48.13 │     │
│                 │ │ 1 │ 11.57 │     │
│                 │ ╰───┴───────╯     │
│ update_location │ false             │
│ update_interval │ 60                │
│                 │ ╭───┬───────╮     │
│ times           │ │ 0 │ 07:00 │     │
│                 │ │ 1 │ 20:00 │     │
│                 │ ╰───┴───────╯     │
╰─────────────────┴───────────────────╯

```

**Comment by bphd** [comment] 2022-12-25 20:32
@flying-sheep what is this tool to format output of syntaxed files?

**Comment by flying-sheep** [comment] 2022-12-26 13:08
https://www.nushell.sh/, it’s pretty great, but also pretty alpha, so only use it if you have time to spend

**Comment by flying-sheep** [comment] 2022-12-26 13:21
@l0drex hmm, I now copied the timer file to where yin-yang expects it and ran `/usr/bin/yin-yang --systemd`, but the timer file still doesn’t get updated.

**Comment by JokaJukka** [comment] 2023-01-02 20:40
@flying-sheep  Are you by any chance running the AUR version of the package?  
If yes, the problem is that AUR packages should not in any way touch the /home directory, and thus the systemd timer file is in the global directory (where the app doesn't expect it to be).

**Comment by bphd** [comment] 2023-01-03 08:28
> @flying-sheep Are you by any chance running the AUR version of the package? If yes, the problem is that AUR packages should not in any way touch the /home directory, and thus the systemd timer file is in the global directory (where the app doesn't expect it to be).

New task, makes the app as functionnal in AUR than in any other repositories

**Comment by flying-sheep** [comment] 2023-01-03 15:50
Yes I use that one. The AUR version should definitely work just as well as any other installation method!

**Comment by JokaJukka** [comment] 2023-01-03 16:02
I hope that the AUR version could get an official recognition (the only official way of installing this app is for now only from source AFAIK). @l0drex?

This is the only issue that would prevent it - I was thinking of fixing it myself, however I'm not sure what the correct solution would be here.  
Arch Packages are installed globally for all users, and thus the timer in home directory makes perfect sense. May I offer a solution that the systemd timer file would create on app runtime (if not already existing)? That would comply with the [Arch package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines), and would solve this problem.

**Comment by flying-sheep** [comment] 2023-01-03 16:48
Seems reasonable. The AUR package could have a `???.install` file that notifies the user of this (unorthodox but in this case justified) behavior.

**Comment by l0drex** [comment] 2023-01-03 20:11
The issue with the timer not being updated should be resolved now, so I will close this.

@bphd about the Konsole part of your request: it currently needs a restart of the application to have an effect, I couldn't find a way to force an update. 
I am not sure what you mean with "skin", if you mean the yakuake design: that is currently not implemented. Create a new issue to request that feature if you want to see this implemented.

**Closed by l0drex** 2023-01-03 20:12 UTC
Labels: bug

**Comment by JokaJukka** [comment] 2023-01-03 20:16
@bphd @flying-sheep FYI the fixed version is already uploaded on AUR.

**Comment by bphd** [comment] 2023-01-04 08:27
> The issue with the timer not being updated should be resolved now, so I will close this.
> 
> @bphd about the Konsole part of your request: it currently needs a restart of the application to have an effect, I couldn't find a way to force an update. I am not sure what you mean with "skin", if you mean the yakuake design: that is currently not implemented. Create a new issue to request that feature if you want to see this implemented.

I don't mean things with what I quoted. It's the official names in all `konsole` products. It behaves like KDE, it has different types of configurations, like KDE could have "Colors" "Plasma Style" and so on... Just tinker a little bit an app of `konsole` family and you should see what I'm talking about. All of that to say that 1) yin-yang don't cover all those aspects; 2)yin-yang doesn't even cover the most important one, who define 90% of the color displayed ("Color scheme & font"); 3) despite what changelog says, yin-yang doesn't cover `konsole` family at all in fact. I never seen any automatic color change of `konsole` family of my life. I always done it myself. yin-yang don't do anything despite what is configured onto it

**Comment by bphd** [comment] 2023-09-22 17:14
Maybe that can help to automatize

coolor=darklight; echo set $coolor; ln --symbolic /home/$USER/.config/yakuakerc-$coolor /home/$USER/.config/yakuakerc; ln --symbolic /home/$USER/.local/share/konsole/Yakuake-$coolor.profile /home/$USER/.local/share/konsole/Yakuake.profile; koi --set-$coolor; yin-yang --set-$coolor
